### ISSUE TITLE
Set up buildroot on the on-campus Raspberry Pi

### ISSUE THREAD

**Issue by thra6614** [cu-ecen-aeld/final-project-thra6614#1]
Set the on-campus Raspberry Pi up with buildroot and try to run an assignment 4 equivalent full test. 

DoD: finder-test.sh returns success

Blockers: #4

**Comment by thra6614** [comment]
thought the full test could run on the image, but didn't know it was the equivalent to runqemu, so pivoted to making sure the finder-test (which the buildroot assignment tested) passed. image shared from Kanin when he was trying to get it running on his board but was able to load the image successfully first using Rufus to load the sd card.

**Comment by suraj-ajjampur** [comment]
Closing an issue means that you need to use this button and close the issue


![Image](https://github.com/cu-ecen-aeld/final-project-thra6614/assets/134313353/99fd2ec1-99db-451b-ac4e-2b50543fe8e3)



Not necessary to have a separate status column.
@thra6614 @Kanin-McGuire  Please take note and change this.
